import Navigation from "@/components/Navigation/navigation";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { Toaster } from "sonner";
import Providers from "./contexts/providers";
import "./globals.css";
import Footer from "@/components/Footer/footer";

const inter = Manrope({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>
          <Navigation />
          {children}
        </Providers>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
